spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alten_test_db
    username: terranga
    password: terranga

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    sn.babacar.alten.test: DEBUG
    org.springframework.security: DEBUG

alten:
  endpoints:
    frontend: ${FRONTEND_URL:http://localhost:4200, http://localhost:3000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
  show-actuator: false
  packages-to-scan: sn.babacar.alten.test.controller